#!/usr/bin/env bash

Set up Nginx to include a custom header in its HTTP response
Add a custom header to the HTTP response (on web-01 and web-02)
hostname_var=$(hostname)
custom_error_page="error_page 404 /custom_404.html;\n location /redirect_me {\n return 301 $scheme://www.google.com;"
custom_header="server {\n\tadd_header X-Served-By $hostname_var;"

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location / {/$custom_error_page/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server {/$custom_header/" /etc/nginx/sites-available/default
sudo service nginx start
