#!/usr/bin/env bash

Debugging nginx (ensure that the service initialization reports that nginx is not running)
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
